[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
max_concurrency = 8

[sysusage]
source = "github"
github = "darold/sysusage"
use_max_tag = true
prefix = "v"

[xmlcopyeditor]
source = "regex"
regex = "files/xmlcopyeditor-linux/([\\d.]+\\d{1})/"
url = "https://sourceforge.net/projects/xml-copy-editor/files/xmlcopyeditor-linux/"
